[package]
name = "schoology"
version = "0.0.1"
authors = ["adumbidiot <nathaniel.daniel23@outlook.com>"]
edition = "2018"

[dependencies]
serde_json= "1"
serde_derive = "1.0"
serde = "1"
hyper = "0.10"
hyper-native-tls = "0.2"
rand="0.4"